#ifndef NUMERICS_HPP
#define NUMERICS_HPP

enum Cmd
{
	JOIN=1,
	NICK,
	PASS,
	USER,
	AUTHENTICATE,
	PLAIN,
	MSG,
	PONG,
	QUIT,
	OPER,
	KILL,
	SQUIT,
	AWAY,
	TIME
};

#define RPL_LOGGEDIN 900
#define RPL_WELCOME 001
#define RPL_YOURHOST 002
#define RPL_CREATED 003
#define RPL_AWAY 301
#define RPL_UNAWAY 305
#define RPL_NOWAWAY 306
#define RPL_MOTD 372
#define RPL_MOTDSTART 375
#define RPL_ENDOFMOTD 376
#define RPL_YOUREOPER 381
#define RPL_TIME 391
#define RPL_USERPARAMS 650
#define ERR_NOOPERHOST 491
#define ERR_CANTKILLSERVER 483
#define ERR_NOPRIVILEGES 481
#define ERR_PASSWDMISMATCH 464
#define ERR_ALREADYREGISTRED 462
#define ERR_NEEDMOREPARAMS 461
#define ERR_NICKNAMEINUSE 433
#define ERR_ERRONEUSNICKNAME 432
#define ERR_NOTREGISTERED 451
#define ERR_CANNOTSENDTOCHAN 404
#define ERR_UNKNOWNCOMMAND 421
#define ERR_NOSUCHSERVER 402
#define ERR_NOSUCHNICK 401
#define ERR_NOTEXTTOSEND 412

#endif