#ifndef NUMERICS_HPP
#define NUMERICS_HPP

enum Cmd {JOIN=1, NICK, PASS, USER, AUTHENTICATE, PLAIN, MSG};

#define RPL_LOGGEDIN 900
#define ERR_NEEDMOREPARAMS 461
#define ERR_UNKNOWNCOMMAND 421

#endif