#ifndef NUMERICS_HPP
#define NUMERICS_HPP

enum Cmd {JOIN=1, NICK, PASS, USER, AUTHENTICATE, PLAIN, MSG, OPER, KILL, SQUIT, AWAY};

#define RPL_LOGGEDIN 900
#define RPL_WELCOME 001
#define RPL_YOURHOST 002
#define RPL_CREATED 003
#define RPL_AWAY 301
#define RPL_UNAWAY 305
#define RPL_NOWAWAY 306
#define RPL_YOUREOPER 381
#define RPL_USERPARAMS 650
#define ERR_NOOPERHOST 491
#define ERR_CANTKILLSERVER 483
#define ERR_NOPRIVILEGES 481
#define ERR_PASSWDMISMATCH 464
#define ERR_ALREADYREGISTRED 462
#define ERR_NEEDMOREPARAMS 461
#define ERR_NICKNAMEINUSE 433
#define ERR_UNKNOWNCOMMAND 421
#define ERR_NOSUCHSERVER 402
#define ERR_NOSUCHNICK 401
#endif